# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('uid', models.TextField()),
                ('oid', models.TextField()),
                ('description', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
    ]
