# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
