# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160702_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='userInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='userInfo1',
            new_name='userInfo',
        ),
    ]
