# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rnc', models.TextField()),
                ('name', models.TextField(null=True)),
                ('phone', models.IntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.category')),
            ],
        ),
        migrations.CreateModel(
            name='dishes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(null=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='groups_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='groups_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('ffid', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.contacts')),
            ],
        ),
        migrations.CreateModel(
            name='menu_category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('master_id', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='orders_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='orders_master',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
                ('status', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.contacts')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
                ('value', models.IntegerField()),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.contacts')),
            ],
        ),
        migrations.AddField(
            model_name='orders_details',
            name='order_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.orders_master'),
        ),
        migrations.AddField(
            model_name='groups_details',
            name='group_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.groups_master'),
        ),
        migrations.AddField(
            model_name='dishes',
            name='menuId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.menu'),
        ),
        migrations.AddField(
            model_name='dishes',
            name='menu_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.menu_category'),
        ),
    ]
