# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
