# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_contacts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.TextField(null=True),
        ),
    ]
