# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20160925_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='user_id',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
