# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20160926_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_master',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
