# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_orders_master_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_master',
            name='menu_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.menu'),
            preserve_default=False,
        ),
    ]
